
spring:
  mail:
    host: smtp.163.com
    username: m18855092854@163.com # 邮箱账号
    password: mail18855092854 # 授权码（下面将会告诉你怎么申请）
    properties:
          mail:
            smtp:
              auth: true
              starttls:
                enable: true
                required: true

