spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test_db?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
#     更新或者创建数据表结构(第一次是创建，后面是更新)
      ddl-auto: update
#    控制台显示SQL
    show-sql: true